const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const NAV=[['Dashboard','ÜBERSICHT'],['team','TEAM'],['players','KADER'],['league','LIGA'],['schedule','SPIELPLAN'],['play','SPIEL SIMULATION'],['transfers','TRANSFERS'],['draft','DRAFT'],['coaches','COACHES'],['stadium','MYBASEBALLPARK'],['sponsors','SPONSOREN'],['teams','TEAMS ÜBERSICHT'],['finance','FINANZEN'],['save','SPEICHERN / LADEN']];
const leagueNames=['Baseball Bundesliga','Katzenelnbogen Regional Baseball League','Baseball Kreisliga'];
const positions=['P','C','1B','2B','3B','SS','LF','CF','RF'];
const names=['Alex','Max','Lukas','Jonas','Felix','Noah','Elias','Leon','Paul','Ben','Finn','Milan','Tom','Jan','Niklas','Moritz','David','Tim','Chris','Daniel'];
let playerData=[];
const state={version:'web-0.1',manager:'Manager',team:null,league:1,season:2025,date:'2025-04-01',games:0,logs:[],stadium:{name:'Baseball-Stadion',capacity:5000,ticket:25,levels:{}},coaches:[],sponsors:[],market:[],draft:[],schedule:[],standings:[]};
function rnd(a,b){return Math.floor(Math.random()*(b-a+1))+a} function pick(a){return a[rnd(0,a.length-1)]} function money(n){return '$'+Math.round(n).toLocaleString('de-DE')}
function makePlayer(i,rmin=45,rmax=75){let r=rnd(rmin,rmax);return {id:'p'+Date.now()+i+Math.random(),name:pick(names)+' '+pick(['Müller','Schmidt','Storm','Weber','Fischer','Klein','Wagner','Becker','Wolf']),age:rnd(18,34),position:pick(positions),rating:r,power:rnd(r-8,r+8),contact:rnd(r-8,r+8),speed:rnd(r-10,r+10),defense:rnd(r-8,r+8),arm:rnd(r-8,r+8),leadership:rnd(35,85),salary:Math.round((150000+r*r*650)/10000)*10000}}
function init(){let saved=localStorage.getItem('gsm-web-save');if(saved){try{Object.assign(state,JSON.parse(saved))}catch(e){}} if(!state.team){createTeam('Katzenelnbogen Storm')} buildMarket(); buildSchedule(); rebuildStandings(); dashboard();}
function createTeam(name){state.team={name, budget:5000000, roster:Array.from({length:30},(_,i)=>makePlayer(i,40,72)), stats:{games:0,wins:0,losses:0}, stadium:{}}; state.logs=['Neues Team gegründet: '+name]; autosave();}
function buildMarket(){state.market=Array.from({length:45},(_,i)=>makePlayer(i+100,35,82))}
function buildSchedule(){state.schedule=[]; for(let i=1;i<=30;i++) state.schedule.push({day:i,opponent:pick(['Allendorf Aces','Kördorf Kings','Rettert Rangers','Limburg Lobsters','Diez Diamonds','Nastätten Navigators']),home:i%2===0,played:false});}
function rebuildStandings(){let base=['Katzenelnbogen Storm','Allendorf Aces','Kördorf Kings','Rettert Rangers','Eisighofen Eagles','Ergeshausen Emperors','Gutenacker Guardians','Herold Hawks','Biebrich Bears','Berndroth Bats','Niedertiefenbach Ninjas','Holzhausen Hammers','Dörsdorf Dragons','Mittelfischbach Marlins','Ebertshausen Elks','Schönborn Sharks'];state.standings=base.map(n=>({name:n,w:n===state.team?.name?state.team.stats.wins:rnd(0,8),l:n===state.team?.name?state.team.stats.losses:rnd(0,8)})).sort((a,b)=>b.w-a.w)}
function autosave(){localStorage.setItem('gsm-web-save',JSON.stringify(state)); updateTop()}
function toast(t){let x=$('#toast');x.textContent=t;x.style.display='block';setTimeout(()=>x.style.display='none',1800)}
function updateTop(){if(!state.team)return;$('#topStatus').innerHTML=`<span>${esc(state.team.name)}</span><span>${money(state.team.budget)}</span><span>S${state.season}</span><span>${state.team.stats.wins}-${state.team.stats.losses}</span>`}
function nav(active){$('#nav').innerHTML='<div class="group">Manager</div>'+NAV.map(([id,label])=>`<button class="${active===id?'active':''}" onclick="go('${id}')">${label}</button>`).join('')}
function go(id){nav(id);({Dashboard:dashboard,team:team,kader:()=>go('players'),players,league,schedule,play,transfers,draft,coaches,stadium,sponsors,teams,finance,save}[id]||dashboard)();}
function shell(title,body){$('#main').innerHTML=`<div class="hero"><h1>${title}</h1><div class="muted">Grand Slam Baseball Manager · Browser Edition</div></div>${body}`;updateTop()}
function dashboard(){nav('Dashboard');let t=state.team, avg=Math.round(t.roster.reduce((a,p)=>a+p.rating,0)/t.roster.length);shell('Manager Dashboard',`<div class="grid"><div class="card">Budget<div class="stat">${money(t.budget)}</div></div><div class="card">Team Rating<div class="stat">${avg}</div></div><div class="card">Bilanz<div class="stat">${t.stats.wins}-${t.stats.losses}</div></div><div class="card">Saison<div class="stat">${state.season}</div></div></div><div class="sectionTitle"><h2>Nächste Schritte</h2></div><div class="grid2"><div class="card"><h3>Nächstes Spiel</h3><p>${state.schedule.find(x=>!x.played)?.opponent||'Keine Spiele'}</p><button class="btn green" onclick="go('play')">Spiel simulieren</button></div><div class="card"><h3>Manager-Aktionen</h3><div class="row"><button class="btn" onclick="go('transfers')">Transfermarkt</button><button class="btn" onclick="go('coaches')">Coach einstellen</button><button class="btn" onclick="go('stadium')">Stadion</button></div></div></div><div class="sectionTitle"><h2>Letzte Ereignisse</h2></div><div class="logs">${state.logs.slice(-15).reverse().map(esc).join('\n')||'Noch keine Ereignisse.'}</div>`)}
function team(){let t=state.team; shell('Mein Team',`<div class="grid2"><div class="card"><h2>${esc(t.name)}</h2><p class="muted">Liga: ${leagueNames[state.league-1]}</p><p>Budget: <b>${money(t.budget)}</b></p><p>Kader: ${t.roster.length} Spieler</p><div class="row"><input id="teamName" value="${esc(t.name)}"><button class="btn" onclick="renameTeam()">Umbenennen</button></div></div><div class="card"><h3>Baseballfeld</h3><div class="field"><div class="diamond"><span class="base b1"></span><span class="base b2"></span><span class="base b3"></span><span class="base home"></span></div></div></div></div>`)}
function renameTeam(){let n=$('#teamName').value.trim();if(n){state.team.name=n;state.logs.push('Team umbenannt in '+n);autosave();team()}}
function players(){let t=state.team; shell('Kader',`<div class="row"><button class="btn" onclick="addPlayer()">Spieler verpflichten</button><button class="btn gray" onclick="sortRoster()">Nach Rating sortieren</button></div><div class="sectionTitle"><h2>${t.roster.length} Spieler</h2></div><table class="table"><thead><tr><th>Spieler</th><th>Pos.</th><th>Alter</th><th>Rating</th><th>Power</th><th>Contact</th><th>Speed</th><th>Gehalt</th></tr></thead><tbody>${t.roster.map(p=>`<tr><td>${esc(p.name)}</td><td>${p.position}</td><td>${p.age}</td><td><b>${p.rating}</b></td><td>${p.power}</td><td>${p.contact}</td><td>${p.speed}</td><td>${money(p.salary)}</td></tr>`).join('')}</tbody></table>`)}
function sortRoster(){state.team.roster.sort((a,b)=>b.rating-a.rating);autosave();players()}
function addPlayer(){let p=state.market.pop();if(!p){toast('Transfermarkt leer');return}let cost=p.salary*2;if(state.team.budget<cost){toast('Budget reicht nicht');state.market.push(p);return}state.team.budget-=cost;state.team.roster.push(p);state.logs.push(`${p.name} für ${money(cost)} verpflichtet.`);autosave();players()}
function league(){rebuildStandings();shell('Liga & Tabelle',`<div class="notice">3-Liga-System: Bundesliga · Katzenelnbogen Regional League · Kreisliga. Auf- und Abstieg werden beim Saisonwechsel verarbeitet.</div><div class="sectionTitle"><h2>${leagueNames[state.league-1]}</h2><span class="pill">Saison ${state.season}</span></div><table class="table"><thead><tr><th>#</th><th>Team</th><th>Siege</th><th>Niederlagen</th><th>Bilanz</th></tr></thead><tbody>${state.standings.map((x,i)=>`<tr><td>${i+1}</td><td>${esc(x.name)}</td><td>${x.w}</td><td>${x.l}</td><td>${(x.w/(x.w+x.l||1)*100).toFixed(1)}%</td></tr>`).join('')}</tbody></table><div class="sectionTitle"><h2>Saison</h2></div><button class="btn" onclick="nextSeason()">Saison abschließen / nächste Saison</button>`)}
function nextSeason(){state.season++;state.games=0;state.date=`${state.season}-04-01`;state.team.roster.forEach(p=>{p.age++;if(p.age<27)p.rating=Math.min(99,p.rating+rnd(1,3));else if(p.age>32)p.rating=Math.max(40,p.rating-rnd(1,4));p.salary=Math.round((150000+p.rating*p.rating*650)/10000)*10000});state.team.budget+=1000000;state.team.stats={games:0,wins:0,losses:0};buildSchedule();state.logs.push('Neue Saison '+state.season+' gestartet.');autosave();league()}
function schedule(){shell('Spielplan',`<table class="table"><thead><tr><th>Tag</th><th>Gegner</th><th>Ort</th><th>Status</th></tr></thead><tbody>${state.schedule.map(g=>`<tr><td>${g.day}</td><td>${esc(g.opponent)}</td><td>${g.home?'Heim':'Auswärts'}</td><td>${g.played?'<span class="pill green">Gespielt</span>':'<span class="pill">Offen</span>'}</td></tr>`).join('')}</tbody></table>`)}
function play(){let g=state.schedule.find(x=>!x.played);if(!g){shell('Spielsimulation','<div class="notice">Alle Spiele dieses Spielplans wurden gespielt.</div>');return}let t=state.team, avg=t.roster.reduce((a,p)=>a+p.rating,0)/t.roster.length, opp=rnd(42,78), weather=pick(['Sonnig','Bewölkt','Windig','Leichter Regen']);let home=g.home?0.03:0, coach=state.coaches.reduce((a,c)=>a+c.boost,0), prob=Math.max(.1,Math.min(.9,.5+(avg+coach-opp)/100+home));let win=Math.random()<prob, ts=win?rnd(3,11):rnd(0,5), os=win?rnd(0,5):rnd(3,11);g.played=true;t.stats.games++;state.games++;win?t.stats.wins++:t.stats.losses++;t.budget+=win?100000:25000;state.logs.push(`${g.home?'Heim':'Auswärts'} vs ${g.opponent}: ${ts}:${os} · ${weather} · ${win?'Sieg':'Niederlage'}`);autosave();shell('Spielsimulation',`<div class="grid"><div class="card"><h3>${esc(t.name)}</h3><div class="stat">${ts}</div></div><div class="card"><h3>${esc(g.opponent)}</h3><div class="stat">${os}</div></div><div class="card"><h3>Wetter</h3><div class="stat">${weather}</div></div><div class="card"><h3>Ergebnis</h3><div class="stat ${win?'success':'danger'}">${win?'SIEG':'NIEDERLAGE'}</div></div></div><div class="sectionTitle"><h2>Spielereignisse</h2></div><div class="logs">${Array.from({length:rnd(8,16)},()=>pick(['Single','Double','Home Run','Strikeout','Walk','Groundout','Flyout','Error'])) .map((x,i)=>`Inning ${Math.min(9,Math.floor(i/2)+1)} · ${x}`).join('\n')}</div><br><button class="btn green" onclick="play()">Nächstes Spiel</button>`)}
function transfers(){shell('Transfermarkt',`<div class="notice">Spieler werden nach Stärke, Alter und Gehalt angeboten. Verpflichtungen wirken direkt auf Budget und Kader.</div><div class="grid2">${state.market.slice(0,24).map((p,i)=>`<div class="playerCard"><div><b>${esc(p.name)}</b><div class="muted small">${p.position} · ${p.age} Jahre · Rating ${p.rating} · ${money(p.salary)}</div></div><button class="btn" onclick="buyMarket(${i})">${money(p.salary*2)}</button></div>`).join('')}</div>`)}
function buyMarket(i){let p=state.market.splice(i,1)[0], cost=p.salary*2;if(state.team.budget<cost){state.market.splice(i,0,p);toast('Budget reicht nicht');return}state.team.budget-=cost;state.team.roster.push(p);state.logs.push(`${p.name} vom Transfermarkt verpflichtet.`);autosave();transfers()}
function draft(){if(!state.draft.length)state.draft=Array.from({length:24},(_,i)=>makePlayer(i+500,35,70));shell('Draft',`<div class="notice">Draft-Pool mit jungen Talenten. Ein Pick fügt den Spieler deinem Kader hinzu.</div><div class="grid2">${state.draft.map((p,i)=>`<div class="playerCard"><div><b>${esc(p.name)}</b><div class="muted small">${p.position} · ${p.age} · Rating ${p.rating}</div></div><button class="btn green" onclick="draftPick(${i})">Draften</button></div>`).join('')}</div>`)}
function draftPick(i){let p=state.draft.splice(i,1)[0];state.team.roster.push(p);state.logs.push(`${p.name} gedraftet.`);autosave();draft()}
function coaches(){if(!state.coaches.length)state.coaches=[{name:'Thomas Keller',boost:.05,cost:180000},{name:'Marco Weber',boost:.06,cost:240000},{name:'Daniel Hoffmann',boost:.08,cost:320000}];shell('Coach-System',`<div class="grid2">${state.coaches.map((c,i)=>`<div class="card"><h3>${c.name}</h3><p>Boost: ${(c.boost*100).toFixed(0)}%</p><p>Vertrag: 1 Saison</p><button class="btn" onclick="hireCoach(${i})">Einstellen · ${money(c.cost)}</button></div>`).join('')}</div><div class="sectionTitle"><h2>Aktive Coaches</h2></div>${state.coaches.filter(c=>c.hired).map(c=>`<div class="playerCard"><b>${c.name}</b><span class="pill green">+${c.boost*100}%</span></div>`).join('')||'<div class="muted">Keine aktiven Coaches.</div>'}`)}
function hireCoach(i){let c=state.coaches[i];if(c.hired||state.team.budget<c.cost){toast(c.hired?'Bereits eingestellt':'Budget reicht nicht');return}c.hired=true;state.team.budget-=c.cost;state.logs.push(`${c.name} als Coach eingestellt.`);autosave();coaches()}
function stadium(){let s=state.stadium;let upgrades=[['stands','Tribünenausbau'],['field','Spielfeldqualität'],['vip','VIP-Logen'],['shops','Merchandise-Shops'],['parking','Parkmöglichkeiten'],['catering','Gastronomie'],['entertainment','Entertainment'],['training','Trainingsanlagen'],['youth','Jugendakademie'],['technology','Stadion-Technologie']];shell('MyBaseballpark',`<div class="grid2"><div class="card"><h2>${esc(s.name)}</h2><p>Kapazität: <b>${s.capacity.toLocaleString()}</b></p><p>Ticketpreis: <b>${money(s.ticket)}</b></p><div class="row"><input id="stadiumName" value="${esc(s.name)}"><button class="btn" onclick="renameStadium()">Umbenennen</button></div></div><div class="card"><h3>Finanzierung</h3><p>Stadionausbau erhöht langfristig Kapazität und Einnahmen.</p><button class="btn green" onclick="upgradeStadium('capacity')">Kapazität +500 · ${money(250000)}</button></div></div><div class="sectionTitle"><h2>10 Upgrade-Kategorien</h2></div><div class="grid2">${upgrades.map(([k,n])=>`<div class="card"><b>${n}</b><p>Level ${s.levels[k]||1}</p><div class="progress"><i style="width:${Math.min(100,(s.levels[k]||1)*10)}%"></i></div><br><button class="btn" onclick="upgradeStadium('${k}')">Upgrade · ${money(100000*((s.levels[k]||1)))}</button></div>`).join('')}</div>`)}
function renameStadium(){let n=$('#stadiumName').value.trim();if(n){state.stadium.name=n;state.logs.push('Stadion umbenannt: '+n);autosave();stadium()}}
function upgradeStadium(k){let lvl=state.stadium.levels[k]||1,cost=250000*lvl;if(k!=='capacity')cost=100000*lvl;if(state.team.budget<cost){toast('Budget reicht nicht');return}state.team.budget-=cost;state.stadium.levels[k]=lvl+1;if(k==='capacity')state.stadium.capacity+=500;state.logs.push(`Stadion-Upgrade: ${k} Level ${lvl+1}`);autosave();stadium()}
function sponsors(){if(!state.sponsors.length)state.sponsors=[{name:'RheinSport',amount:300000,bonus:'.02'},{name:'Storm Energy',amount:500000,bonus:'.03'},{name:'Baseball Pro',amount:800000,bonus:'.04'}];shell('Sponsoren',`<div class="grid2">${state.sponsors.map((s,i)=>`<div class="card"><h3>${s.name}</h3><p>Prämie: <b>${money(s.amount)}</b></p><p>Sponsor-Bonus: ${s.bonus}</p><button class="btn green" onclick="signSponsor(${i})">Vertrag unterschreiben</button></div>`).join('')}</div>`)}
function signSponsor(i){let s=state.sponsors[i];if(s.signed){toast('Bereits aktiv');return}s.signed=true;state.team.budget+=s.amount;state.logs.push(`Sponsorvertrag mit ${s.name}: +${money(s.amount)}`);autosave();sponsors()}
function teams(){rebuildStandings();shell('Teams Übersicht',`<div class="grid2">${state.standings.map((x,i)=>`<div class="card"><h3>${esc(x.name)}</h3><p>Bilanz: ${x.w}-${x.l}</p><div class="progress"><i style="width:${Math.min(100,x.w/(x.w+x.l||1)*100)}%"></i></div></div>`).join('')}</div>`)}
function finance(){let payroll=state.team.roster.reduce((a,p)=>a+p.salary,0);shell('Finanzen',`<div class="grid"><div class="card">Budget<div class="stat">${money(state.team.budget)}</div></div><div class="card">Jahresgehälter<div class="stat">${money(payroll)}</div></div><div class="card">Stadionkapazität<div class="stat">${state.stadium.capacity}</div></div><div class="card">Ticketpreis<div class="stat">${money(state.stadium.ticket)}</div></div></div><div class="sectionTitle"><h2>Finanzlog</h2></div><div class="logs">${state.logs.slice(-30).reverse().map(esc).join('\n')}</div>`)}
function save(){shell('Speichern / Laden',`<div class="grid2"><div class="card"><h3>Browser-Speicher</h3><p>Das Spiel speichert automatisch in localStorage.</p><button class="btn green" onclick="autosave();toast('Gespeichert')">Jetzt speichern</button><button class="btn red" onclick="if(confirm('Spielstand wirklich löschen?')){localStorage.removeItem('gsm-web-save');location.reload()}">Spielstand löschen</button></div><div class="card"><h3>JSON Export / Import</h3><button class="btn" onclick="exportSave()">Spielstand exportieren</button><input type="file" id="importFile" accept="application/json" onchange="importSave(event)"></div></div><div class="sectionTitle"><h2>Port-Hinweis</h2></div><div class="notice">Diese Browser-Portierung nutzt die Daten und Feature-Spezifikation deines Originalprojekts. Die Desktop-Tkinter-Oberfläche kann im Browser nicht direkt ausgeführt werden; die Web-Oberfläche bildet die Manager-Funktionen neu ab.</div>`)}
function exportSave(){let blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=(state.team?.name||'grand-slam')+'_save.json';a.click()}
function importSave(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{Object.assign(state,JSON.parse(r.result));autosave();location.reload()}catch(err){toast('Ungültiger Spielstand')}};r.readAsText(f)}
init();
